### ISSUE TITLE
Support flatpak.

### ISSUE THREAD

**Issue by rokejulianlockhart** [VioletGiraffe/file-commander#287]
My rationale is available at "http://github.com/safing/portmaster-packaging/issues/43#issue-956312378#:~:text=It%20shall%20allow,to%20support%20this.".

I am thankful for any assistance.

**Comment by VioletGiraffe** [comment]
Hello, thanks for your suggestion. I might look into flatpak, but is there something wrong with the Appimage package that's already provided for download? Does it not work for you?

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
This comment is response to “http://github.com/VioletGiraffe/file-commander/issues/287#issuecomment-1002650929”.

Unlike AppImage, textual management of flatpak packages is possible, which is able to allow more consistent distribution and deployment / general management.

Additionally, they are able to be – and frequently or usually are – more conservant of space, more secure, and more supportive of new features, because they are able to utilise run-times. This is similar to regular packages for Linux, but they are able to operate via almost any distribution of Linux, and consequently are frequently superior.

**Comment by rokejulianlockhart** [comment]
Superb. Thanks.

**Comment by VioletGiraffe** [comment]
I have not looked into flatpak as AppImage does the job. Please feel free to contribute flatpak support if you'd like to!
